### DISCUSSION TITLE
Group connection options into a single dictionary option

### DISCUSSION THREAD

**Discussion by Jorge-Rodriguez** [ansible-collections/ansible.mysql#134] [Ideas]
We have seen issues before that were not so much problems with the code but with the code semantics and the understandability of it. As it stands, our module options and the database connection options are at the same level, this causes some confusion as to what is the purpose of each option.

What I propose here is to group all connection options into a single dictionary type option instead, so that where we currently support something of the form:

```yaml
- community.mysql.mysql_user:
      name: new_user
      password: new_password
      login_user: admin_user
      login_password: admin_password
      [...]
```
We would, either instead or additionally, support something like:

 ```yaml
- community.mysql.mysql_user:
      connection_options:
          user: admin_user
          password: admin_password
          [...]
      name: new_user
      password: new_password
```

In addition to this, I've noticed that the MySQLdb connector seems to always use an SSL connection if possible (ssl_mode: PREFERRED), even if there are no ssl options provided and therefore one would assume that no SSL connection would occur (which is the behaviour of the pymysql connector).
There is a flag in both connectors to explicitly disable an SSL connection. I suggest that we add an `use_tls` option to expose this flag to the end user.

**Comment by Jorge-Rodriguez** [comment]
Ping @bmalynovytch @Andersson007

**Comment by bmalynovytch** [comment]
I agree with your suggestions @Jorge-Rodriguez 👍

**Comment by Andersson007** [comment]
> We would, either instead or additionally, support something like:

Additional support of `connection_options:` sounds good to me

**Comment by Jorge-Rodriguez** [comment]
About the `use_tls` option, there's a divergence between providers. While pymysql exposes a Boolean flag (`disable_ssl` if memory serves), MySQLDb exposes an enumeration instead, mapped directly from MySQL's `ssl_mode`.

I feel inclined to expose `ssl_mode` in the module options. @bmalynovytch @Andersson007 what do you guys think.

Then, when it comes to `connection_options`, what do you think would be better, to have a generally flat structure, or to group TLS-related options into their own key, e.g.:

```yaml
connection_options:
    tls:
        ca_cert: CA.pem
[...]
```
