### DISCUSSION TITLE
How to generate a pre-hashed sha2 password

### DISCUSSION THREAD

**Discussion by msilveirabr** [ansible-collections/ansible.mysql#565] [Q&A]
Hi.
How can we use a pre-generated hash password to use with this combination:
```yaml
- name: MySQL | Ensure MySQL users are present
  mysql_user:
    plugin: caching_sha2_password
    name: "{{ mysql_username }}"
    host: "{{ mysql_host }}"
    # password: cleartext_insecure_password
    plugin_auth_string: "HOW_DO_I_GENERATE_THIS????"
    priv: "{{  mysql_priv | default(['*.*:USAGE']) | join('/') }}"
```

The closest content to an answer I could find was this : https://github.com/hashcat/hashcat/issues/2305

But I have no idea (yet) on how to accomplish this... 
BTW is it really necessary to create the hash as described in the mentioned url?
