### DISCUSSION TITLE
mysql_db: Add support for sql_log_bin

### DISCUSSION THREAD

**Discussion by hyvs** [ansible-collections/ansible.mysql#699] [Ideas]
The `mysql_user` module has an interesting feature that allows creating users without writing to the binary log:

```
community.mysql.mysql_user:
    name: foo
    ...
    sql_log_bin: false
```

This feature is particularly useful for provisioning all servers in a primary-replica cluster without breaking replication or needing to identify the primary server at any given time.

Could this be a valuable addition to the `mysql_db` module?
