### ISSUE TITLE
mysql_user always reports changes when `privs: *.*:ALL`

### ISSUE THREAD

**Issue by Jorge-Rodriguez** [ansible-collections/ansible.mysql#104]
##### SUMMARY
According to the [docs](https://dev.mysql.com/doc/refman/8.0/en/show-grants.html) MySQL 8 no longer reports `ALL` privileges as `ALL` but as the explicit list of granted privileges.

This causes the privilege parser to always detect a change in privileges

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

mysql version 8 and later

##### STEPS TO REPRODUCE

```yaml
- name: create user1 state=present with a password
      mysql_user:
        <<: *mysql_params
        name: '{{ user_name_1 }}'
        password: '{{ user_password_1 }}'
        priv: '*.*:ALL'
        state: present
```

##### EXPECTED RESULTS

Result is not changed on subsequent runs

##### ACTUAL RESULTS

Result is always changed
