### ISSUE TITLE
mysql_user: password change detect

### ISSUE THREAD

**Issue by markuman** [ansible-collections/ansible.mysql#128]
##### SUMMARY
When creating a user with `mysql_user`, it always returned "change", even if the password does not change.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.10.6
  config file = None
  configured module search path = ['/home/m/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/m/.local/lib/python3.9/site-packages/ansible
  executable location = /home/m/.local/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

##### STEPS TO REPRODUCE

```yaml
- name: Simple select query to acme db
  community.mysql.mysql_query:
    ca_cert: rds-combined-ca-bundle.pem
    login_host: "{{ MARIADB_HOST }}"
    login_password: "{{ MARIADB_PASSWORD }}"
    login_port: 3306
    login_user: "{{ MARIADB_USER }}"
    query: "SELECT password('{{ item.password }}') as p"
  register: out

- name: "add or update user"
  mysql_user:
    ca_cert: rds-combined-ca-bundle.pem
    login_host: "{{ MARIADB_HOST }}"
    login_password: "{{ MARIADB_PASSWORD }}"
    login_port: 3306
    login_user: "{{ MARIADB_USER }}"
    name: "{{ item.name }}"
    host: "%"
    encrypted: yes
    password: "{{ out.query_result[0][0].p }}"
    priv: "{{ item.privileges | join('/') | replace('ALL', ALL) }}"
    resource_limits: "{{ item.resource_limits | default(DEFAULT_RESOURCE_LIMITS) }}"
    state: present
```

##### EXPECTED RESULTS
No change detect when the requested password `SELECT password('{{ item.password }}') as p` is already the same hash in the mysql.user table.

##### ACTUAL RESULTS
Ansible returns always with a change.
