### ISSUE TITLE
why login_unix_socket can't use for remote connection?

### ISSUE THREAD

**Issue by Fanduzi** [ansible-collections/ansible.mysql#148]
##### SUMMARY

ansible version 2.9.18
in the doc:
login_unix_socket: The path to a Unix domain socket for local connections.

My mysql only has `with grant option` for root@localhost, which means I can only ssh to the mysql server and connect via socket. But community.mysql.mysql_user's login_unix_socket only works on `connection: local`?
Unlike older versions of ansible's mysql_user module

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.9.18
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: {{ username }}
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    name: "{{ username }}"
    host: "%"
    priv: "{{ priv }}"
    update_password: on_create
    plugin: 'mysql_native_password'
    plugin_auth_string: "{{ password }}"
```

##### ACTUAL RESULTS

```paste below
{"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```
