### ISSUE TITLE
Setting root password on Fedora 34 (mariadb-server-10.5.9-5) not possible

### ISSUE THREAD

**Issue by robertdebock** [ansible-collections/ansible.mysql#164]
##### SUMMARY
On Fedora 34, which uses `mariadb-server-10.5.9-5.fc34.x86_64
`, setting a root-password fails:

```
unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2003, \"Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)\")"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysq_user

##### ANSIBLE VERSION

```
ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/Users/redaxted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.2 (default, Mar 26 2021, 15:28:17) [Clang 12.0.0 (clang-1200.0.32.29)]
```

##### CONFIGURATION
```
% ansible-config dump --only-changed
# No output
```

##### OS / ENVIRONMENT

Controller: Mac OS X
Managed node: Fedora 34

##### STEPS TO REPRODUCE
I'm using Molecule to test [this code](https://github.com/robertdebock/ansible-role-mysql/blob/master/handlers/main.yml#L11).

```yaml
- name: set root password
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: ""
    name: root
    password: SomePassWord
    state: present
  become: yes
  become_user: mysql
```

##### EXPECTED RESULTS
A changed root password.

##### ACTUAL RESULTS

[See the ci output](https://github.com/robertdebock/ansible-role-mysql/runs/2489964661?check_suite_focus=true#step:6:1334):

```
RUNNING HANDLER [ansible-role-mysql : set root password] ***********************
fatal: [mysql-fedora-latest]: FAILED! => changed=false 
  msg: 'unable to connect to database, check login_user and login_password are correct or /var/lib/mysql/.my.cnf has the credentials. Exception message: (1698, "Access denied for user ''root''@''localhost''")'
```
Interesting: [Fedora 33](https://github.com/robertdebock/ansible-role-mysql/runs/2489964637?check_suite_focus=true) and [Fedora Rawhide](https://github.com/robertdebock/ansible-role-mysql/runs/2489964679?check_suite_focus=true) both work. It must be something with Fedora, although I can't figure out what the issue is.

**Comment by Andersson007** [comment]
@robertdebock hello, thanks for reporting the issue! You ran it in docker, right? We experienced a problem with running postgresql in the fedora 34 container today too. Dbus seems to be preinstalled there but the system can't launch it and postgresql resp. I didn't try it in a VM though.
If anybody could check this issue on a Fedora 34 VM and report the result, it would be cool.

**Comment by robertdebock** [comment]
I reproduced the error on a VM (Fedora 34): same issue. Good hint though.

About PostgreSQL: that could be an unrelated issue.

**Comment by Andersson007** [comment]
@robertdebock thanks for the feedback!

1) is it relevant only for `root` user? if you run same playbook with same password against another user, does it work well?
2) does the password contain symbols like `£` that can require (I don't know how to say properly) something like "extended encoding"?
3) do you use same mariadb server version on both Fedora33 and Fedora34?

**Comment by robertdebock** [comment]
Hi @Andersson007.

Answers:
1. It's relevant for multiple users; I tried `root` and `newroot`.
2. No, I used: `s3Cur31t4.`.
3. I use the mariadb version that comes packaged with Fedora:

|Fedora version|MariaDB version|
|---------------|----------------|
|33|mariadb-10.4.18-1.fc33|
|34|mariadb-10.5.9-5.fc34|
|35 (rawhide)|mariadb-10.5.9-5.fc35|

**Comment by Andersson007** [comment]
@robertdebock thanks for the information! Hope someone can take a closer look at the issue soon.

**Comment by bmalynovytch** [comment]
The error is strange: it says it's trying to "connect" to localhost but reports "No such file or directory" which means it was trying to look on the local filesystem.
There must be a mess with the socket connection (default because using localhost as hostname).
Have you tried to connect to "127.0.0.1" or specify the path of the Unix socket ?

**Comment by Andersson007** [comment]
@robertdebock could you please take a look at the bmalynovytch's comment above? We'd be grateful for feedback. Thanks

**Comment by robertdebock** [comment]
I'm very sorry to admit, this was my mistake...

For future reference, here is what was incorrect.

I had the user (`become: true` and `become_user: {{ mysql_user }}`) variable per distribution and version. All distribution and versions used `root`, except Fedora-34, which used `mysql`.

This was the **INCORRECT** handler:

```yaml
- name: set root password
  community.mysql.mysql_user:
    login_unix_socket: "{{ mysql_socket }}"
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"
    state: present
  become: yes
  become_user: "{{ mysql_user }}"                                                                            
```

I removed `become` and `become_user` and the role works again.
