### ISSUE TITLE
mysql_replication changemaster does not support GET_SOURCE_PUBLIC_KEY

### ISSUE THREAD

**Issue by ehudkaldor** [ansible-collections/ansible.mysql#165]
in mysql 8.0, setting replication source on the replica requires the parameter GET_SOURCE_PUBLIC_KEY=1 so the replica will grab the pub key from the source. This parameter does not exist in the collection

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```
<empty>
```

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE

see below

```yaml
- mysql_replication:
    mode: changemaster
    master_host: "{{ primary_database }}"
    master_port: "{{ mysql_port }}"
    master_user: "{{ mysql_replication_user_name }}"
    master_password: "{{ mysql_replication_user_password }}"
    master_auto_position: 1
    get_master_public_key: 1

```
##### EXPECTED RESULTS
success

##### ACTUAL RESULTS

see below

```
Unsupported parameters for (mysql_replication) module: get_master_public_key Supported parameters include: ca_cert, client_cert, client_key, config_file, connect_timeout, login_host, login_password, login_port, login_unix_socket, login_user, master_auto_position, master_connect_retry, master_host, master_log_file, master_log_pos, master_password, master_port, master_ssl, master_ssl_ca, master_ssl_capath, master_ssl_cert, master_ssl_cipher, master_ssl_key, master_user, mode, relay_log_file, relay_log_pos"
```
