### ISSUE TITLE
mysql_query: To include the extra-vars

### ISSUE THREAD

**Issue by tarunm97** [ansible-collections/ansible.mysql#188]
##### SUMMARY

Hi Team, can we add the extra-vars field in the mysql_query ansible module, just like we have in the **mysql_db** module for dump state(dump_extra_args)
```
- name: Dump databases without including triggers
  community.mysql.mysql_db:
    state: dump
    name: foo
    target: /tmp/dump.sql
    dump_extra_args: --skip-triggers
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

mysql_query

##### ADDITIONAL INFORMATION

will be good if we add this feature for example i got stucked while automating this mysql query

```yaml
mysql  -uroot -p'' --skip-column-names -A -e"SELECT CONCAT('truncate table ',table_schema,'.',table_name,';') FROM information_schema.tables  WHERE table_schema='plparchivetest'"
```

I tried to automate the query, everything is fine apart from the "**-skip-column-names -A**", how to pass this.
```
- name: truncate the tables
  community.mysql.mysql_query:
       login_user: root
       login_password: "{{ mysql_password }}"
       login_unix_socket: /var/run/mysqld/mysqld.sock
       query: "SELECT CONCAT('truncate table ',table_schema,'.',table_name,';') FROM information_schema.tables  WHERE table_schema='plparchivetest'"
```
