### ISSUE TITLE
"No database selected" when creating user on MariaDB

### ISSUE THREAD

**Issue by Mythobeast** [ansible-collections/ansible.mysql#213]
##### SUMMARY

Attempting to create a user on a fresh database fails with the following message.
FAILED! => {"changed": false, "msg": "(1046, 'No database selected')"}

Workaround: By adding the following line to ~/.my.cnf I was able to make this work as expected.
database='mysql'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mysql.mysql_user

##### ANSIBLE VERSION
```
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/Users/rapplean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.5.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/rapplean/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 12:37:55) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
# /Users/rapplean/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 2.1.1

# /usr/local/Cellar/ansible/4.5.0/libexec/lib/python3.9/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 2.1.1
```

##### CONFIGURATION
No output from the config dump

##### OS / ENVIRONMENT
Darwin mylaptop.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

##### STEPS TO REPRODUCE

```yaml
- name: Add appuser user
  community.mysql.mysql_user:
    login_unix_socket: "{{mariadb_socket}}"
    config_file: "~/.my.cnf"
    name: appuser
    password: "{{appuser_password}}"
    priv: "app_db_name:ALL"
    state: present
```

##### EXPECTED RESULTS
User should be created

##### ACTUAL RESULTS
FAILED! => {"changed": false, "msg": "(1046, 'No database selected')"}

```
FAILED! => {"changed": false, "msg": "(1046, 'No database selected')"}
```

**Comment by Andersson007** [comment]
@Mythobeast hello, thanks for the issue!
Could you please run the task with  `-vvv` and put the traceback in the issue?

**Comment by aadlung** [comment]
I get the same error, does this help?
Error looks like https://github.com/ansible/ansible/issues/68070

Ansible Task:
```
- name: Create MySQL users
  mysql_user:
    name: "{{ exampleuser_mysql_user }}"
    host: "localhost"
    login_unix_socket: "{{ mysql_socket }}"
    password: "{{ exampleuser_mysql_password }}"
    priv: "*.*:USAGE/performance_schema:SELECT"
    state: "present"
    append_privs: "no"
    encrypted: "no"
```

Mysql Module:
```
$ ansible-galaxy collection list community.mysql

# /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 2.3.1  

# /Users/exampleuser/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 2.3.1 
```

Shell Output:
```
ansible-playbook [core 2.11.6] 
  config file = /Users/exampleuser/.ansible.cfg
  configured module search path = ['/Users/exampleuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/exampleuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

```
The full traceback is:
  File "/tmp/ansible_mysql_user_payload_i42ci874/ansible_mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 434, in main
  File "/tmp/ansible_mysql_user_payload_i42ci874/ansible_mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py", line 361, in user_mod
    privileges_grant(cursor, user, host, db_table, priv, tls_requires, maria_role)
  File "/tmp/ansible_mysql_user_payload_i42ci874/ansible_mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py", line 702, in privileges_grant
    cursor.execute(query, params)
  File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
fatal: [adlsrv2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "ca_cert": null,
            "check_hostname": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": "/run/mysqld/mysqld.sock",
            "login_user": null,
            "name": "exampleuser",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "plugin": null,
            "plugin_auth_string": null,
            "plugin_hash_string": null,
            "priv": "*.*:USAGE/performance_schema:SELECT",
            "resource_limits": null,
            "sql_log_bin": true,
            "state": "present",
            "tls_requires": null,
            "update_password": "always",
            "user": "exampleuser"
        }
    },
    "msg": "(1046, 'No database selected')"
}
```

**Comment by rsicart** [comment]
Specifying the option `database` in `[client]` group of  your `~/my.cnf` file does change anything?

**Comment by aadlung** [comment]
I tried it with
```
[client]
database=mysql
```
In the ~/my.cnf or ~/.my.cnf on the **ansible client** where I run the playbook, none of that worked.

I've also tried to add it to the **ansible server** in the above mentioned `/root/.my.cnf` - then I get another error because my config tries to set permission to the performance_schema database.

```
fatal: [srv2]: FAILED! => {"changed": false, "msg": "(1146, \"Table 'mysql.performance_schema' doesn't exist\")"}
```

The config I use is:
```
- name: Create MySQL users
  mysql_user:
    name: "{{ metricbeat_mysql_user }}"
    host: "localhost"
    login_unix_socket: "{{ mysql_socket }}"
    password: "{{ metricbeat_mysql_password }}"
    priv: "*.*:USAGE/performance_schema:SELECT"
    state: "present"
    append_privs: "no"
    encrypted: "no"
  no_log: false
```
