### ISSUE TITLE
Documentation for configuration using requirements.yml is wrong

### ISSUE THREAD

**Issue by arcmop** [ansible-collections/ansible.mysql#22]
Hi, 

Documentation says:
```YAML
---
collections:
  - name: community.mysql
    version: v1.0.0
```

But "v" letter in version is incorrect and result with error using command ansible-galaxy collection install .... (Standalone or using Ansible Tower/AWX)

```YAML
---
collections:
  - name: community.mysql
    version: 1.0.0
```

Best regards.
