### ISSUE TITLE
Unable to create user with privilege REPLICATION CLIENT on MariaDB 10.5.5

### ISSUE THREAD

**Issue by ghost** [ansible-collections/ansible.mysql#232]
##### SUMMARY
When trying to create a new user using the mysql_user module it error if you try to user REPLICATION CLIENT as a priv. As per the MariaDB docs this was renamed in v10.5.2 to BINLOG MONITOR but the old name should alias to this. In v2.1.0 of community.mysql it works as intended but in v2.3.0 it errors.

It would be nice to be able to run the same Ansible against a MariaDB 10.4 and 10.5 server.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.mysql.mysql_user

##### ANSIBLE VERSION

```
ansible [core 2.11.6]
config file = /codebuild/output/src941743992/src/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/local/bin/ansible
python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
jinja version = 3.0.2
libyaml = True
```

##### COLLECTION VERSION

```
community.mysql 2.3.0
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

OS Ubuntu 20.04.3 LTS
MariaDB 10.5.5

##### STEPS TO REPRODUCE

```yaml
- name: "Create user"
  mysql_user:
    name: "user"
    host: "localhost"
    password: "password"
    login_user: root
    login_password: "password"
    priv: "*.*:SELECT,PROCESS,SHOW DATABASES,SHOW VIEW,EXECUTE,SUPER,CREATE TEMPORARY TABLES,LOCK TABLES,REPLICATION SLAVE,REPLICATION CLIENT,EVENT,TRIGGER,RELOAD"
    state: present
```

##### EXPECTED RESULTS

User created with privileges set as above.

##### ACTUAL RESULTS

Error received as below

```paste below
 TASK [ansible-mariadb : Create user] **************************
fatal: [hostname]: FAILED! => changed=false 
  msg: 'invalid privileges string: Invalid privileges specified: frozenset([''REPLICATION CLIENT''])' 
```
