### ISSUE TITLE
mysql_user: Add support for appending privileges

### ISSUE THREAD

**Issue by NicolasGoeddel** [ansible-collections/ansible.mysql#263]
##### SUMMARY
At the moment you have to specify all the different privileges a user can have on certain databases in one go:
```yaml
 - mysql_user:
   name: user
   password: password
   priv: "db1.*:SELECT/db2.*:ALL"
```
But sometimes you just want to add a certain privilege for a new database without changing the privileges you gave the user in the past to other databases.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_user

##### ADDITIONAL INFORMATION
If you only have one mysql user with one password and this user already has granted some privileges to some databases you know nothing about and you have to make sure they do not change, you can not simply use mysql_user because it breaks everything. Therefore I suggest a new option `priv_append` which will append new privileges if they are in no conflict with existing ones.

This could look like this:

Both of these playbooks should do the same:
```yaml
 - mysql_user:
   name: user
   password: password
   priv: "db1.*:SELECT/db2.*:ALL"
   priv_append: true
```

```yaml
 - mysql_user:
   name: user
   password: password
   priv: "db1.*:SELECT"
   priv_append: false

 - mysql_user:
   name: user
   password: password
   priv: "db2.*:ALL"
   priv_append: true
```
