### ISSUE TITLE
Disable hostname check

### ISSUE THREAD

**Issue by ldesgrange** [ansible-collections/ansible.mysql#28]
##### SUMMARY
When connecting to MySQL with REQUIRE SSL, when the hostname check fails the task (`mysql_db`, `mysql_user`) throws an exception. It could be useful to be able to ignore the hostname check.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community/mysql/plugins/module_utils/mysql.py`

##### ADDITIONAL INFORMATION
The hostname check can fail for self-signed certificate (dev environment), some managed MySQL provided by cloud providers seem to provide wrong certificates…

For PyMySQL, this feature request would be a mapping of the `check_hostname` options in the `ssl` argument (see [answer on stackoverflow](https://stackoverflow.com/a/46930971)).

```yaml
- name: Create a new database with name 'bobdata'
  mysql_db:
    name: bobdata
    state: present
    login_host: somehost.local
    login_user: someuser
    login_password: somepassword
    check_hostname: no
```

**Comment by Jorge-Rodriguez** [comment]
@ldesgrange can you provide a way to reproduce? If we implement this we need a reliable way to test the integration.

**Comment by ldesgrange** [comment]
@Jorge-Rodriguez sorry, I forgot to provide that in the ticket description. You can reproduce this issue by doing the following:
- install a debian 10 in a virtual machine (like VirtualBox)
- install mysql 8 on it:
```
wget https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb
sudo apt update
sudo apt install mysql-community-server
sudo mysql -p
show variables like 'ssl%'; -- display SSL configuration, mysql has self signed certificates by default (debian's mariadb package does not), files are in /var/lib/mysql/
create user 'bob'@'%' identified by 'foobar';
grant ALL on bobdata.* to 'bob'@'%';
alter user 'bob'@'%' require ssl; -- force ssl to be used for that user
flush privileges;
```
- Run a task (from the ansible host, not from within the vm) like this (after copying `ca.pem` and `server-cert.pem` from the vm then merging them together in `server.pem`):
```
- name: Create a new database with name 'bobdata'
  community.mysql.mysql_db:
    name: bobdata
    state: present
    login_host: "vm"
    login_user: "bob"
    login_password: "foobar"
    ca_cert: "server.pem"
```
- Error message (similar one when trying to connect with the IP address instead of the hostname): `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'vm'. (_ssl.c:1108)`
