### ISSUE TITLE
mysql_user expires password on second run

### ISSUE THREAD

**Issue by dotneutron** [ansible-collections/ansible.mysql#295]
##### SUMMARY
I want to create non-root users with `mysql_user`. Everything goes fine when I run the playbook once. The second time I run it, the task is again marked as `changed` despite having `msg: User unchanged` in the result. The issue is that `password_expired` is changed to `true` inside the `mysql.user` table after the second run, which makes it impossible for users to log in without a workaround. All subsequent runs mark the task as `ok`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
ansible [core 2.12.2]
  config file = /path/to/project/ansible.cfg
  configured module search path = ['/Users/neutron/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/neutron/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /Users/neutron/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.1.1

# /opt/homebrew/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 2.3.3
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/path/to/project/ansible.cfg) = True
DEFAULT_HOST_LIST(/path/to/project/ansible.cfg) = ['/path/to/project/inventory']
DEFAULT_STDOUT_CALLBACK(/path/to/project/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/path/to/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Host OS: Ubuntu 20.04 LTS
Docker MySQL OS: See [Dockerfile](https://github.com/docker-library/mysql/blob/546838ab256ad36a9f6571e900deb7c4040cd383/8.0/Dockerfile.debian) for `mysql:8`
MySQL client: PyMySQL
MySQL settings:
* default_password_lifetime: 0

##### STEPS TO REPRODUCE
```yaml
- name: Create MySQL users
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_port: "{{ mysql_host_port }}"
        plugin: caching_sha2_password
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.priv }}"
        host: "%"
        update_password: on_create
        state: present
      with_items:
        - name: bobby
          password: blablabla
          priv: "{{ mysql_database }}.*:SELECT,INSERT,UPDATE,DELETE"
      tags: mysql-users
      register: mysql_user_create
```

##### EXPECTED RESULTS
The task should not expire the users' passwords on the second run or cause any other changes.

##### ACTUAL RESULTS
Despite the modification(s) caused by the second run, the task result has `msg: User unchanged`.
