### ISSUE TITLE
mysql_role closes connection twice

### ISSUE THREAD

**Issue by betanummeric** [ansible-collections/ansible.mysql#329]
##### SUMMARY
The mysql_role module closes the mysql connection too often.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module community.mysql.mysql_role

##### VERSIONS
```paste below
ansible 2.10.8
python 3.9.2
community.mysql 3.1.2
python3-pymysql 0.9.3-2
MariaDB 10.6.4
```

##### STEPS TO REPRODUCE
tested with this playbook task:
```yaml
- name: add testrole
  community.mysql.mysql_role:
    state: present
    login_unix_socket: /tmp/mysql-3306.sock
    append_members: yes
    append_privs: yes
    members: []
    name: testrole1
    priv:
      "test1.*": "SELECT,UPDATE,DELETE,INSERT"
    set_default_role_all: no
```

##### EXPECTED RESULTS
Only closing the connection once, without warnings.

##### ACTUAL RESULTS
Ansible logs a warning because it fails to close an already closed connection.
```
[WARNING]: Module invocation had junk after the JSON data: Exception ignored in: <bound method mysql_connect.<locals>._conn_patch
of <pymysql.connections.Connection object at 0x7f79e64d9d30>> Traceback (most recent call last):   File "/tmp/ansible_community.my
sql.mysql_role_payload_ajeef4h3/ansible_community.mysql.mysql_role_payload.zip/ansible_collections/community/mysql/plugins/module_
utils/mysql.py", line 112, in _conn_patch   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 721, in close
raise err.Error("Already closed") pymysql.err.Error: Already closed
```
