### ISSUE TITLE
mysql.user tries to set password on second run with update_password = "on_create" 

### ISSUE THREAD

**Issue by hubiongithub** [ansible-collections/ansible.mysql#334]
Hello

I did not find an issue describing my problem, tested witch community_mysql  3.1.2

##### SUMMARY
create user in mysql (8) with password validation configured:
password_history = 5
second run tries to update password (with the same value) which results in
 "msg": "(3638, \"Cannot use these credentials for 'bobby@localhost' because they contradict the password history policy\")"}
see below for ansible code used

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql.user

##### ANSIBLE VERSION
```
2.9.27
```

##### COLLECTION VERSION
```
3.1.2
```

##### OS / ENVIRONMENT
Ubuntu 20.04 LTS on both sides

##### STEPS TO REPRODUCE
```yaml
---
- hosts: all
  tasks:
    - name: Create MySQL users
      become: yes
      community.mysql.mysql_user:
        plugin: caching_sha2_password
        name: "{{ item.name }}"
        plugin_auth_string: "{{ item.password }}"
        priv: "{{ item.priv }}"
        host: "localhost"
        update_password: "on_create"
        state: present
      with_items:
        - name: bobby
          password: ...
          priv: "sakila.*:SELECT"
```
and a smal .ini file describing which hosts to use

##### EXPECTED RESULTS
If update_password is set to "on_create" I would assume no alter user ... is issued at all, as long the user exists.

I'm not sure if it is possible to analyse authentication_string from mysql.user with the current password in the yaml
code in plugins/module_utils/user.py says (line 267)
            if plugin_auth_string and current_plugin[1] != plugin_auth_string:
                # this case can cause more updates than expected,
                # as plugin can hash auth_string in any way it wants
                # and there's no way to figure it out for
                # a check, so I prefer to update more often than never
                update = True
that it isn't, which will cause the same problem if update_password is set to always. 
But at least if update_password is set to on_create this code should not run at all.

##### ACTUAL RESULTS
```
msg": "(3638, \"Cannot use these credentials for 'bobby@localhost' because they contradict the password history policy\")"}
```

Probably this also will fail on every other plugin also, but I only tested caching_sha2_password.

Beside the actual error if I don't use plugin_auth_string but password, I get the user created but with an empty authentication_string,
the documentation could be a bit more clear when to use which variable. (Or the code could could handle "password" differently depending on the plugin given, so one who makes the plugin variable don't need to code around this depending on which plugin is used)

Regards
