### ISSUE TITLE
mysql_user: add option to reuse password of existing user when creating a new one

### ISSUE THREAD

**Issue by betanummeric** [ansible-collections/ansible.mysql#344]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_user

##### SUMMARY
In MySQL/MariaDB the password is a property of a username-source-address-combination. However, I want to use the same password per username, for all source addresses of that username. (I only need password authentication, I'm not sure how this generalizes to other authentication methods).
For that, I would need to reuse the existing password when creating a new user with the same name. This new behavior could be enabled with a new value for the existing module argument: `update_password: on_new_username`.

For further processing, I need a `password_changed` boolean in the module return object. This could/should also be used to indicate whether the password of an existing user was changed.

I can submit a PR for this.

##### EXAMPLE

When I request a new user with
```yaml
- name: add user with other IP
  community.mysql.mysql_user:
    state: present
    name: "test"
    host: "2001:db8::1"
    password: "newpassword"
    update_password: on_new_username
```

- and the user `"test"@"localhost"` already exists with password `existingpassword`, I would like to get the user `"test"@"2001:db8::1"` with password `existingpassword` (and ignore the `newpassword`). `password_changed` should be `false`.
- and there are multiple preexisting users with the same name, but varying passwords, I suggest to fall back to the supplied `newpassword`. `password_changed` should be `true`.
- and there is no user called `test`, the `"test"@"2001:db8::1"` user is created normally with the password `newpassword`. `password_changed` should be `true`.

**Comment by hubiongithub** [comment]
Hello @betanummeric 

Can't this be solved outside of mysql.user by using items and adding hosts to the list as required:

```
- name: add user with other IP
  community.mysql.mysql_user:
    state: present
    name: "test"
    host: {{ item }}
    password: "password you want for these users"
    update_password: on_create/always       # depending on wether ansible is the truth or the database over time
  with_items:
    - host1
    - host2
    - ...
```

This works for all kind of auth methods and no need to read the hashes ...
