### ISSUE TITLE
changeprimary doesn't turn off SSL on primary_ssl: no

### ISSUE THREAD

**Issue by svenedge** [ansible-collections/ansible.mysql#393]
##### SUMMARY
Setting `primary_ssl: no` just _doesn't add_ `MASTER_SSL=1`, rather than adding `MASTER_SSL=0`, meaning you can't turn off SSL if it's already turned on.

https://github.com/ansible-collections/community.mysql/blob/2a3f8f6506ffa173bbb4d1401312e11bcf6d2a12/plugins/modules/mysql_replication.py#L580-L581

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
      community.mysql.mysql_replication:
        mode: changeprimary

##### ANSIBLE VERSION

```
ansible [core 2.12.5]
  config file = /Users/sven.edge/repos/devops-ansible-rmm/ansible.cfg
  configured module search path = ['/Users/sven.edge/repos/devops-ansible-rmm/library']
  ansible python module location = /usr/local/Cellar/ansible/5.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/sven.edge/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /usr/local/Cellar/ansible/5.8.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 2.3.7
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE

```yaml
community.mysql.mysql_replication:
    mode: changeprimary
    login_host: 127.0.0.1
    login_port: 3306
    login_user: "{{ a }}"
    login_password: "{{ b }}"
    fail_on_error: yes

    primary_host: "{{ c }}"
    primary_port: "{{ d }}"
    primary_log_file: "{{ e.File }}"
    primary_log_pos: "{{ e.Position }}"
    primary_user: "{{ f }}"
    primary_password: "{{ g }}"
    primary_ssl: no
    check_hostname: no

```

##### EXPECTED RESULTS

```
mysql -Ee 'show slave status' | grep Master_SSL_Allowed
           Master_SSL_Allowed: Yes
```

run ansible

```
mysql -Ee 'show slave status' | grep Master_SSL_Allowed
           Master_SSL_Allowed: No
```

##### ACTUAL RESULTS

```
mysql -Ee 'show slave status' | grep Master_SSL_Allowed
           Master_SSL_Allowed: Yes
```
