### ISSUE TITLE
community.mysql.mysql_info appears not to support the !includedir option in /root/.my.cnf

### ISSUE THREAD

**Issue by chriscroome** [ansible-collections/ansible.mysql#394]
The `community.mysql.mysql_info` module (I've only tested with version `3.3.0`) fails to gather info when a `/root/.my.cnf` file exists that simply contains a `!includedir` option, see the [Option File Inclusions documentation for MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/option-files.html), for example:

```
!includedir /root/.my.cnf.d/
```

When the directory exists but has no content:

```bash
ls -lah /root/.my.cnf.d/
total 8.0K
drwxr-xr-x  2 root root 4.0K May 12 15:28 .
drwx------ 11 root root 4.0K Jun  8 09:43 ..
```
And the Ansible used is:

```yml
    - name: Query MariaDB / MySQL info
      community.mysql.mysql_info:
        filter:
          - databases
          - users
          - version
        return_empty_dbs: true
        login_unix_socket: /run/mysqld/mysqld.sock
      register: mysql_info
```

The Ansible error message is:

```
fatal: [example.org]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: File contains no section headers.\nfile: '/root/.my.cnf', line: 1\n'!includedir /root/.my.cnf.d/\\n'"}
```

If the `/root/.my.cnf` file is deleted it solves the issue, if a file is added to the directory that is included that does contain a section header, for example, `/root/.my.cnf.d/foo.cnf`:

```
[mysqladmin]
```

Then the error message is identical which indicates to me that the `community.mysql.mysql_info` module might not have any support for `!includedir` in option files?

**Comment by Andersson007** [comment]
@chriscroome hello, thanks for reporting the issue!

This is probably related to the python driver (PyMySQL, mysqlclient) as the collection does nothing with a config file but just assigns it to its (driver's) `read_default_file` argument.

As i can see the message, returned by the driver:
```File contains no section headers.\nfile: '/root/.my.cnf', line: 1\n'!includedir /root/.my.cnf.d/\\n'```

The [driver's doc](https://pymysql.readthedocs.io/en/latest/modules/connections.html) is saying `read_default_file – Specifies my.cnf file to read these parameters from under the [client] section.`.
Could you please add `[client]` sections to both the files and try again?

Waiting for your feedback

**Comment by chriscroome** [comment]
Thanks, I will do some more testing and get back to you but I'm not going to have time to do this today.

**Comment by chriscroome** [comment]
@Andersson007 why are `~/.my.cnf` file being read when `config_file` has not been specified and why is it a problem if a `~/.my.cnf` file doesn't contain a `[client]` section?

**Comment by Andersson007** [comment]
@chriscroome
> why are ~/.my.cnf file being read when config_file has not been specified

I don't know, it was introduced a long time ago. I guess because it's read when you connect using `mysql` and other utilities, i.e. it's a kind of the default config file there and module's developers decided to follow the same strategy (it's my guess).

>why is it a problem if a ~/.my.cnf file doesn't contain a [client] section?

Did you try to add it and it helped?
If yes, i would better ask the PyMySQL/mysqlclient connector developers:) We can see the `[client]` section mentioned in the official connector's doc https://pymysql.readthedocs.io/en/latest/modules/connections.html

**Comment by chriscroome** [comment]
Adding ` [client]` section at the top of the file, so that `/root/.my.cnf` becomes:

```
[client]
!includedir /root/.my.cnf.d/
```

Does result in the following task working:

```yml
    - name: Query MariaDB / MySQL info using /run/mysqld/mysqld.sock
      community.mysql.mysql_info:
        filter:
          - databases
          - users
          - version
        return_empty_dbs: true
        login_unix_socket: /run/mysqld/mysqld.sock
      register: mysql_info
```

However if it is added at the bottom of the file, so that `/root/.my.cnf` becomes:

```
!includedir /root/.my.cnf.d/
[client]
```

Then it causes it to fail:

```
fatal: [example.org]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: File contains no section headers.\nfile: '/root/.my.cnf', line: 1\n'!includedir /root/.my.cnf.d/\\n'"}
```

Since (I believe) a `/root/.my.cnf` file is valid without a `[client]` section or with a empty `[client]` section at the end of the file I wouldn't have expected this to have caused a failure of the module.

Would having the ability to set `config_file` to False and for the file to then not be read be an option to work around the problem caused by valid defaults files?
