### ISSUE TITLE
community.mysql.mysql_db appears not to support relative paths when importing databases

### ISSUE THREAD

**Issue by chriscroome** [ansible-collections/ansible.mysql#395]
The [MariaDB sys schema](https://github.com/iwindfree/mariadb-sys) cannot be imported using `community.mysql.mysql_db`, for example this Ansible:

```yml
    - name: MariaDB sys repo directory present
      ansible.builtin.file:
        path: /usr/local/src/mariadb-sys
        state: directory
        mode: 0755

    - name: MariaDB sys schema repo present
      ansible.builtin.git:
        repo: https://github.com/iwindfree/mariadb-sys.git
        dest: /usr/local/src/mariadb-sys
        clone: true 
        version: bcd090461189f35dcadfae77f87ca233a6587f95

    - name: Import the MariaDB sys schema
      community.mysql.mysql_db:
        name: all
        state: import
        target: /usr/local/src/mariadb-sys/mariadb_sys_install.sql
        login_unix_socket: /run/mysqld/mysqld.sock
```

Fails with:

```
ERROR at line 11: Failed to open file './views/v_threads.sql', error: 2
```

I suspect this is because [relative links are used](https://github.com/iwindfree/mariadb-sys/blob/master/mariadb_sys_install.sql#L11) in the SQL, for example:

```sql
SOURCE ./views/v_threads.sql
```

The `ansible.builtin.shell` module can be used since is supports `chdir`, for example:

```yml
    - name: Import the sys schema using the shell module
      shell: mysql < ./mariadb_sys_install.sql
      args:
        chdir: /usr/local/src/mariadb-sys
```

Could adding support for `cd`'ing into to the directory that contains the file to be imported or adding a `chdir` option to the module be considered as a feature request to solve this problem?
