### ISSUE TITLE
mysql_db: problem with zeroes in database name

### ISSUE THREAD

**Issue by imThief** [ansible-collections/ansible.mysql#409]
##### SUMMARY
mysql_db replaces all zeroes with asterisks in database name when processes it. There is no problems with any other digits. {% raw %} block or literal notation doesn't helps.
UPD: all names in paths/dump file names/etc are affected too.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_db

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fox/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
community.mysql 2.3.5
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/user/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = user
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles', '/etc/ansible/dev', '/etc/ansible/servers', '/etc/ansible/services']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 22.04

##### STEPS TO REPRODUCE

Use zeroes in database name.

```yaml
vars:
  data:
    database:
      name: 'dump_000'
      source: 'dump-000.sql'
      host: 172.17.0.1
      login_user: root
      login_pwd: 123
tasks:
  - name: Verifying database
    become: yes
    mysql_db:
      name: "{{ item.database.name }}"
      state: present
      encoding: utf8
      login_unix_socket: "{{ mysql_socket }}"
      login_user: "{{ item.database.login_user }}"
      login_password: "{{ item.database.login_pwd }}"
      config_file: /dev/null
    loop: "{{ data }}"
    loop_control:
      label: "Processing database {{ item.database.name|d('<None>') }}"
```

##### EXPECTED RESULTS

```
changed: [localhost] => (item=Processing database dump_000) => changed=true
  ansible_loop_var: item
  db: dump_000
  db_list:
  - dump_000
```

##### ACTUAL RESULTS

All zeroes in db name were replaced by asterisks

```paste below
changed: [localhost] => (item=Processing database dump_000) => changed=true
  ansible_loop_var: item
  db: dump_************************
  db_list:
  - dump_************************
```
