### ISSUE TITLE
Cannot create user with random password from variable

### ISSUE THREAD

**Issue by djboni** [ansible-collections/ansible.mysql#458]
##### SUMMARY

Cannot create user with random password from variable

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.5]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.7.0  
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/Documents/ansible/inventory.yml']
INTERPRETER_PYTHON(/home/user/.ansible.cfg) = auto
```

##### OS / ENVIRONMENT

Host: Ubuntu 22.04
Targets: Ubuntu 22.04, Debian 11

##### STEPS TO REPRODUCE

See playbook below:

```yaml
---
- name: Not creating user with random password from variable

  # Tested on Ubuntu 22.04 and Debian 11
  hosts: test-ubuntu

  vars:
    # This does NOT work:
    mariadb_user_password1: "{{ lookup('ansible.builtin.password', '/dev/null', length=4, chars='hexdigits') }}"

    # This does work:
    mariadb_user_password2: "test"

  tasks:
    - name: Install MariaDB
      apt:
        name:
          - mariadb-server
          - python3-mysqldb
        state: present

    - name: Create user named 'database_user1' with privileges to the database
      mysql_user:
        name: database_user1
        host: localhost
        state: present
        password: "{{ mariadb_user_password1 }}"

    - name: Create user named 'database_user2' with privileges to the database
      mysql_user:
        name: database_user2
        host: localhost
        state: present
        password: "{{ mariadb_user_password2 }}"

    - name: Restart MariaDB
      action: service name=mariadb state=restarted enabled=yes

    - name: Print MySQL user and password
      debug:
        msg: "CANNOT LOGIN: mysql -u database_user1 -p{{ mariadb_user_password1 }} "

    - name: Print MySQL user and password
      debug:
        msg: "CAN LOGIN: mysql -u database_user2 -p{{ mariadb_user_password2 }} "
```

##### EXPECTED RESULTS

I expect to be able to login with both database_user1 and database_user2.

##### ACTUAL RESULTS

Cannot login with database_user1. Can login with database_user2.

```paste below
root@test-debian:~# mysql -u database_user1 -p2eaE
ERROR 1045 (28000): Access denied for user 'database_user1'@'localhost' (using password: YES)

root@test-debian:~# mysql -u database_user2 -ptest
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 33
Server version: 10.5.15-MariaDB-0+deb11u1 Debian 11
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MariaDB [(none)]> 
```
