### ISSUE TITLE
msg": "Error granting privileges, invalid priv string: ALL"

### ISSUE THREAD

**Issue by razerrazer** [ansible-collections/ansible.mysql#462]
##### SUMMARY

When I run my playbook I try to set up a simple user with a database from your FAQ.

Creating a database : works

But when it tries to set a user with privileges it doesn't work.
I've tried like 100 different types of 'bob.*:ALL' etc.. but nothing works

with and without "" and '' 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```
mysql_user
```
##### ANSIBLE VERSION
```
ansible [core 2.13.5]

```

##### COLLECTION VERSION

```
Collection        Version
----------------- -------
community.general 5.7.0
community.mysql       3.5.1
also tested it with: community.mysql       3.5.0
```

##### CONFIGURATION

```
#Ansible config:
- name: Create .my.cnf
  template:
   src: "templates/my.cnf.j2"
   dest: "/root/.my.cnf"
   owner: root
   group: root
   mode: 0600

- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Create database user with name bob
  mysql_user:
    name: bob
    password: {{my_db_password}}
    priv: '*.*:ALL'
    state: present
```

##### OS / ENVIRONMENT
```
Ansible Host: Linux Mint 21
Target:  Debian 11 / MariaDB 10.9
```

##### ACTUAL RESULTS

```
The full traceback is:
"/tmp/ansible_mysql_user_payload_p_u38pra/ansible_mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py", line 725, in privileges_grant
    raise InvalidPrivsError("Error granting privileges, invalid priv string: %s" % priv_string)
fatal: [172.16.200.37]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "ca_cert": null,
            "check_hostname": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "force_context": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "name": "bob",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "plugin": null,
            "plugin_auth_string": null,
            "plugin_hash_string": null,
            "priv": "*.*:ALL",
            "resource_limits": null,
            "sql_log_bin": true,
            "state": "present",
            "subtract_privs": false,
            "tls_requires": null,
            "update_password": "always",
            "user": "bob"
        }
    },
    "msg": "Error granting privileges, invalid priv string: ALL"
}

```

**Comment by razerrazer** [comment]
Same issue with MariaDB 10.5.15

Anyone ?

**Comment by razerrazer** [comment]
I can confirm this is a bug when you trying to install mysql user on a Debian 11 machine.

It's working as it should in Rocky Linux v9 without any problems.
So i guess this is something you have to take a deeper look at.

**Comment by markuman** [comment]
If the `ALL` priv is supported depends on the database provider.  
In case of AWS RDS (_as a database provider_), `ALL`  is also not available. The only way to work around this is to name every needed privilege.

Basically you name the privileges in a `ALL`  variable and replace the `ALL` in a string.  

```yml
---
- name: prepare nextcloud container
  hosts: localhost
  connection: local

  tasks:
    - name: test
      vars:
        mysql_parameters: &mysql_params
          login_user: root
          login_password: mariadb
          login_host: 127.0.0.1
          login_port: 33066
        ALL: "ALTER,ALTER ROUTINE,CREATE,CREATE ROUTINE,CREATE TEMPORARY TABLES,CREATE VIEW,DELETE,DROP,EVENT,EXECUTE,INDEX,INSERT,LOCK TABLES,REFERENCES,SELECT,SHOW VIEW,TRIGGER,UPDATE"

      block:
        - name: start nextcloud container
          register: out
          community.docker.docker_container:
            name: mariadb_test_container
            image: mariadb:10.5.15
            state: started
            auto_remove: true
            recreate: true
            container_default_behavior: no_defaults
            published_ports:
              - "127.0.0.1:{{ mysql_parameters.login_port }}:3306"
            env:
              MARIADB_ROOT_PASSWORD: "{{ mysql_parameters.login_password }}"

        - name: mariadb container needs some sec for initialization
          pause:
            seconds: 10

        - name: create user with two grants
          mysql_user:
            <<: *mysql_params
            name: testuser
            password: testpassword
            update_password: on_create
            priv: "{{ '*.*:ALL' | replace('ALL', ALL) }}"
            state: present

      always:
        - name: stop mariadb test container
          community.docker.docker_container:
            name: mariadb_test_container
            state: absent
```

So imho, this is not a community.mysql issue at first place.

**Comment by laurent-indermuehle** [comment]
@razerrazer have you tried with `ALL PRIVILEGES` instead of `ALL`. I think `ALL` is an alias and is not present on all mysql flavors. So normally you would write `GRANT ALL PRIVILEGES TO db.* ON user@localhost`.

**Comment by redeyesdemonkyo** [comment]
For what is worth I had this error but the issue was related to the account ansible was using to login to MySQL (v8) to try to grant that `ALL`  `priv` did not actually have the `grant` permission.  Had to first give the login account `grant` permission and after that ansible was able to create the users with `ALL` priv

**Comment by Andersson007** [comment]
> For what is worth I had this error but the issue was related to the account ansible was using to login to MySQL (v8) to try to grant that `ALL` `priv` did not actually have the `grant` permission. Had to first give the login account `grant` permission and after that ansible was able to create the users with `ALL` priv

@redeyesdemonkyo thanks for sharing the solution! So
- Can we close the issue?
- Should the doc be improved anyhow or it's fine as is?

**Comment by arLevi** [comment]
In my case, this particular instance of mysql was part of a replication cluster 
which was configured with a `--super-read-only` flag/variable.

In that case, no Ansible commands can be run on it
See:
https://www.percona.com/blog/using-the-super_read_only-system-variable/
which says:

> It is well known that replica servers in a master/slave configuration,
> to avoid breaking replication due to duplicate keys, missing rows or
> other similar issues, should not receive write queries.

**Comment by pschiffe** [comment]
I see this error now with `mariadb:11.3` official docker image as  a server (user and db name is the same):
```
failed: [host] (item={'key': 'user', 'value': 'pw'}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "user", "value": "pw"}, "msg": "Error granting privileges, invalid priv string: ALL PRIVILEGES , params: ('user', '%'), query: GRANT ALL PRIVILEGES ON `user`.* TO %s@%s , exception: (1044, \"Access denied for user 'root'@'%' to database 'user'\")."}
```

Tried both `ALL` and `ALL PRIVILEGES` variants.

`mariadb:11.2` works fine without this error.

**Comment by laurent-indermuehle** [comment]
Hi @pschiffe and thanks for reporting the issue on 11.3.

I believe we test only long term support versions, which are atm 10.4, 10.5, 10.6 and 10.11. The v11 is still kind of a beta. I'm not saying we won't fix an issue on v11, because at some point they will release a LTS on that branch too. Just saying we haven't tested it yet.

@pschiffe, could you paste the whole community.mysql.mysql_user task so we can see what you tried to achieve please. It could be that the user you're using doesn't have enough rights to create a new user?

**Comment by pschiffe** [comment]
Yeah, I understand, thanks for getting back to me. Here's the task. The user is `root`, and before this task, I'm creating other users with privileges like `priv: '*.*:RELOAD, PROCESS, LOCK TABLES, BINLOG MONITOR, CONNECTION ADMIN'` and `priv: '*.*:SELECT, PROCESS, REPLICATION CLIENT, RELOAD'` and these tasks works. The issue is only with `ALL` priv:

```yaml
- name: Create db users
  community.mysql.mysql_user:
    name: '{{ item.key }}'
    password: '{{ item.value }}'
    host: '%'
    priv: '{{ item.key }}.*:ALL'
    login_user: root
    login_password: '{{ mariadb_root_pw }}'
    login_host: '{{ db_result.container.NetworkSettings.Networks[mariadb_network_name].IPAddress }}'
    state: present
  loop: '{{ mariadb_users | dict2items }}'
```
