### ISSUE TITLE
Mysql-Query

### ISSUE THREAD

**Issue by Davidffry** [ansible-collections/ansible.mysql#51]
##### SUMMARY

Cannot select more than 1 parameters in the Select statement
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Mysql-query
##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /home/david/ansible/ansible-repot/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1

##### STEPS TO REPRODUCE

just launch this task 

```yaml
- name: Simple select query to target_table db
  community.mysql.mysql_query:
    login_db: "datab"
    login_password: "0123456789"
    login_user: "9876543210"
    login_host: "localhost"
    query: "Select name, description from target_table "
  register: r_query
```

##### EXPECTED RESULTS

    "query_result": [
        [
            {
                "name": 2,
                "description ": "/srv/abc/ijk/def",
            },
            {
                "name": 2,
                "description ": "/srv/abc/ijk/def",
            },
            {
                "name": 2,
                "description ": "/srv/abc/ijk/def",
            },
            ...
        ]
    ]

##### ACTUAL RESULTS

the module separate in n independant queries

```paste below
...
            "query": [
                "select name",
                " description from target_table "
            ],
            "single_transaction": false
        }
    },
    "msg": "Cannot execute SQL 'select id' args [None]: (1054, \"Unknown column 'name' in 'field list'\")"
```

**Comment by Andersson007** [comment]
@Davidffry hi, thanks for reporting the issue! will look at this ASAP

**Comment by Davidffry** [comment]
Tips, it maybe come from the ansible module param query which do repr() so i tried somethings but i did not success

I add ```
module.params['query'].join(',')
```
It did not work.

**Comment by Andersson007** [comment]
@Davidffry @Jorge-Rodriguez after a quick look i figured out that:
```
query:
- "Select name, description from target_table "
```
should work. Because the type of `query` is a list with string elements. If a single-row query contains commas, Ansible thinks this is a list and split it. Maybe we could just change the documents?
I can later try to change the parameter's type to `raw` but not sure this is a good idea

**Comment by Andersson007** [comment]
the prev comment has just been changed, sorry, i'm not a native speaker and when i'm in rush my comments turn out to be a complete mess:)

**Comment by Davidffry** [comment]
alright! it's work, I close the issue

**Comment by Andersson007** [comment]
@Davidffry i definitely should try to experiment with `raw` type;) At least i must change the documentation, i reopened the issue as a reminder:)

**Comment by Andersson007** [comment]
i created https://github.com/ansible-collections/community.mysql/pull/53

**Comment by Andersson007** [comment]
@Davidffry i've just released community.mysql 1.1.1 that contains the change.
The tarball is already in [galaxy](https://galaxy.ansible.com/community/mysql),
so you can download and install it [manually](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-collections-with-ansible-galaxy) from there (alternatively you can wait until next Ansible fix release but the previous one was yesterday).
I'd be grateful for any feedback. Thanks!

**Comment by Davidffry** [comment]
Works for the two:
```yaml
- name: Simple select query to retrieve db
  community.mysql.mysql_query:
    login_db: "{{item.db}}"
    login_password: "{{item.pwd}}"
    login_user: "{{item.u}}"
    login_host: "{{item.url | default('localhost')}}"
    query: 
      - "{{item.query}}"
  register: r_query
  loop:
    - {name: "ressources", query: "select id, user12 from resource", db: dataB , u: 012, pwd: 123 }
    - {name: "commands", query: "select name, line, command.description,count(*) as uses from command left join service on command.id = service.check_command group by name", db: dataB , u: 012, pwd: 123 }
    - {name: "templateservicesdetails", query: "select nht.name, ns.description, nc.name, nc.line, group_concat(nsccp.parameter) as params from service ns inner join host_template nht on ns.host_template=nht.id inner join service_template_inheritance nsti on ns.id=nsti.source_service inner join command nc on ns.check_command=nc.id left join service_check_command_parameter nsccp on ns.id = nsccp.service group by nc.name order by nht.name ASC;", db: dataB , u: 012, pwd: 123 }
    - {name: "hostservicesdetails", query: "select nh.name, ns.description, nc.name, nc.line, group_concat(nsccp.parameter) as parameters from service ns inner join host nh on nh.id = ns.host inner join command nc on ns.check_command = nc.id inner join service_check_command_parameter nsccp on ns.id = nsccp.service group by nh.name order by nh.name ASC;", db: dataB , u: 012, pwd: 123 }
```

or 

```yaml
- name: Simple select query to retrieve db
  community.mysql.mysql_query:
    login_db: "{{item.db}}"
    login_password: "{{item.pwd}}"
    login_user: "{{item.u}}"
    login_host: "{{item.url | default('localhost')}}"
    query: "{{item.query}}"
  register: r_query
  loop:
    - {name: "ressources", query: "select id, user12 from resource", db: dataB , u: 012, pwd: 123 }
    - {name: "commands", query: "select name, line, command.description,count(*) as uses from command left join service on command.id = service.check_command group by name", db: dataB , u: 012, pwd: 123 }
    - {name: "templateservicesdetails", query: "select nht.name, ns.description, nc.name, nc.line, group_concat(nsccp.parameter) as params from service ns inner join host_template nht on ns.host_template=nht.id inner join service_template_inheritance nsti on ns.id=nsti.source_service inner join command nc on ns.check_command=nc.id left join service_check_command_parameter nsccp on ns.id = nsccp.service group by nc.name order by nht.name ASC;", db: dataA , u: 012, pwd: 123 }
    - {name: "hostservicesdetails", query: "select nh.name, ns.description, nc.name, nc.line, group_concat(nsccp.parameter) as parameters from service ns inner join host nh on nh.id = ns.host inner join command nc on ns.check_command = nc.id inner join service_check_command_parameter nsccp on ns.id = nsccp.service group by nh.name order by nh.name ASC;", db: dataC , u: 012, pwd: 123 }
```

I know it can be optimized ;)
