### ISSUE TITLE
Optionally decrypt and parse MySQL's login path file

### ISSUE THREAD

**Issue by flybyray** [ansible-collections/ansible.mysql#511]
##### SUMMARY
Decrypt and parse MySQL's login path file.

See also: https://dev.mysql.com/doc/refman/8.0/en/mysql-config-editor.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`plugins/module_utils/mysql.py`

##### ADDITIONAL INFORMATION
https://github.com/PyMySQL/myloginpath
See also: https://dev.mysql.com/doc/refman/8.0/en/mysql-config-editor.html

```yaml
---
  - name: Playbook
    hosts: mysql_servers
    tasks:
    - name: Collect all possible information using passwordless root access
      community.mysql.mysql_info:
          login_path: client

```
