### ISSUE TITLE
Possible recurrence of issue #151 following latest release of community.mysql?

### ISSUE THREAD

**Issue by paulh-rtr** [ansible-collections/ansible.mysql#546]
##### SUMMARY
A Github Action which we run on a weekly basis, and which calls an Ansible playbook which in turn calls community.mysql, is failing since this weekend on all calls to community.mysql 

Nothing has changed in the codebase; this was confirmed as working last weekend, and so I presume the issue is with the most recent release 3.7.0.  Running the playbook by hand, in a different environment with an earlier version of community.mysql, works.

For example see below (with some details redacted):
```
- name: create heartbeat user
  community.mysql.mysql_user:
<snip>
    state: present
  when: db_role == "{{ master_role }}"
```

This produces an error like the following:
```
fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

**Note:** The error message would seem to be the same as in this issue: https://github.com/ansible-collections/community.mysql/issues/151.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user, mysql_query, possibly others

##### ANSIBLE VERSION
```
ansible.posix:1.5.2
```
##### COLLECTION VERSION
```
community.mysql:3.7.0
```

##### OS / ENVIRONMENT
Github Action environment as described below:
```
Current runner version: '2.304.0'
Runner name: 'infra-runners-default-tr8[2](https://github.com/RentTheRunway/mysql/actions/runs/4904303710/jobs/8757254064#step:1:2)k-cqkkn'
Runner group name: 'infra-runners'
Machine name: 'infra-runners-default-tr82k-cqkkn'
GITHUB_TOKEN Permissions

Starting galaxy role install process
- downloading role 'google_cloud_ops_agents', owned by googlecloudplatform
- downloading role from https://github.com/GoogleCloudPlatform/stackdriver-ansible-role/archive/master.tar.gz
- extracting googlecloudplatform.google_cloud_ops_agents to /home/runner/.ansible/roles/googlecloudplatform.google_cloud_ops_agents
- googlecloudplatform.google_cloud_ops_agents (master) was installed successfully
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/ansible-posix-1.5.2.tar.gz to /home/runner/.ansible/tmp/ansible-local-508_auvsywe/tmpfntsf2t8/ansible-posix-1.5.2-zzhqpkox
Installing 'ansible.posix:1.5.2' to '/home/runner/.ansible/collections/ansible_collections/ansible/posix'
ansible.posix:1.5.2 was installed successfully
...
Downloading https://galaxy.ansible.com/download/community-mysql-3.7.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-508_auvsywe/tmpfntsf2t8/community-mysql-3.7.0-bubguzl8
Installing 'community.mysql:3.7.0' to '/home/runner/.ansible/collections/ansible_collections/community/mysql'
community.mysql:3.7.0 was installed successfully
Downloading https://galaxy.ansible.com/download/community-general-6.6.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-508_auvsywe/tmpfntsf2t8/community-general-6.6.0-jbn55ez8
Installing 'community.general:6.6.0' to '/home/runner/.ansible/collections/ansible_collections/community/general'
community.general:6.6.0 was installed successfully
```

##### STEPS TO REPRODUCE
Some example code blocks which are failing:

```
- name: create heartbeat user
  community.mysql.mysql_user:
<snip>
    state: present
  when: db_role == "{{ master_role }}"
```

```
- name: Provision <stuff>
  community.mysql.mysql_query:
    login_db: mysql
    query:
      - "SET sql_log_bin = 0"
      - "REPLACE INTO tablename <etc...{{variable1}} {{variable2}}...  etc>"
    named_args:
      variable1: "{{ variable1 }}"
      variable2: "{{ variable2 }}"
    single_transaction: yes
```

##### EXPECTED RESULTS
Call to community.mysql.mysql_user, mysql_query etc. completes as requested

##### ACTUAL RESULTS
Actual results for the 2 examples as above:

```
TASK [<role name> : create heartbeat user] ***********************
fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

```
TASK [<role name> : Provision <stuff>] ***
fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

**Comment by alexgit2k** [comment]
I can confirm this, having the same issue after upgrading from 3.6.0 to 3.7.0.
2 Workarounds:
1. Downgrading via Shell:
```
rm -rf .ansible/collections/ansible_collections/community/mysql
ansible-galaxy collection install community.mysql:==3.6.0
```

2. Configuration via `requirements.yml`:
```
collections:
  - name: community.mysql
    version: "=3.6.0"
```

**Comment by alexgit2k** [comment]
Just found out that the problem occurs only on our CentOS 7 machine:
- **Not working**: CentOS 7 with Ansible 2.9.27, Python 2.7.5, MySQLdb (package MySQL-python)
- **Working**: AlmaLinux 9 with Ansible 2.13.3, Python 3.9.14, MySQLdb (package python3-mysqlclient)

Maybe it has something to do with Python 2.

@paulh-rtr Which versions are you using?

**Comment by paulh-rtr** [comment]
@alexgit2k Thanks for looking into the issue. The environment on which we encountered this issue is Github Actions, which is a CI/CD provided by Github, not unlike Jenkins.

I don't have much if any control over that environment, but looks like it is pulling the following:
```
0s
Current runner version: '2.304.0'
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
```

Looks like there is a comprehensive list at https://github.com/actions/runner-images/blob/releases/ubuntu22/20230426/images/linux/Ubuntu2204-Readme.md

Could well be Python 2; there is a note stating that it will be removed from the image on May 15. I'd be more than happy to report back if that effectively fixes the issue. In the meantime, am using the workaround you suggested.

**Comment by 31239899** [comment]
We're hitting the same error. It started suddenly on May 8 UTC (no issues on May 7 or before).

Managed clients: RHEL/CentOS 7, Python 2.7.5, MySQL-python 1.2.5
Source: AWX, Ansible core 2.12.5, community.mysql 3.7.0

I can work around it by removing `MySQL-python` on the clients and installing `python2-PyMySQL`.

~Our execution environment image has not changed in over a month, so I'm skeptical that this has anything to do with 3.7.0.~ (EDIT: see my comment [here](https://github.com/ansible-collections/community.mysql/issues/546#issuecomment-1544206590).) Ansible playbooks are also unchanged. No package/configuration changes on the clients.

**Comment by alexgit2k** [comment]
Here it worked till last Thursday (4th) and it did not worked again on Monday (8th) unless we forced 3.6.0. And 3.7.0 was released last Friday (5th).

**Comment by 31239899** [comment]
I stand corrected. It turns out AWX was re-pulling requirements and overriding what was in our execution environment (very unintuitive behavior!). So 3.7.0 is the problem after all. It seems it just took a few days from the tagged release here to make its way into Galaxy and down to our server before we saw problems.

**Comment by Andersson007** [comment]
Hi everyone, thanks for the issue report and the discussion!

@Jorge-Rodriguez i think this thing was introduced by https://github.com/ansible-collections/community.mysql/pull/177, would you like to take a look? Is it what we expected?

**Comment by betanummeric** [comment]
@paulh-rtr Can you provide the full call of `community.mysql.mysql_user` with all arguments? You can censor secret values.

**Comment by alexgit2k** [comment]
@betanummeric Here is our configuration:
```
- name: MariaDB users
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mariadb_users }}"
  no_log: true
```

With
```
mariadb_users:
  - name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    host: localhost
    priv: '*.*:ALL'
  - name: "{{ dbuser_dbmanage }}"
    password: "{{ dbpasse_dbmanage }}"
    host: '%'
    priv: '*.*:ALL'
```
