### ISSUE TITLE
mysql_query check mode using transaction

### ISSUE THREAD

**Issue by drzraf** [ansible-collections/ansible.mysql#613]
##### SUMMARY
mysql_query should support check mode using `start transaction`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_query

##### ADDITIONAL INFORMATION

> Would be useful to check queries (eg: UPDATE/INSERT) beforehand

```mysql
START TRANSACTION;
UPDATE foobar SET abc='xyz';
ROLLBACK;
```

##### Quick and dirty proposal:

https://github.com/ansible-collections/community.mysql/blob/32718ca2956b2b776d633710a940d45c4d517431/plugins/modules/mysql_query.py#L171-L173

```python
 if check_mode:
    query = ["START TRANSACTION", *query, "ROLLBACK"]
```

##### Current workaround

```yaml
    - mysql_query:
        login_db: db
        query:
          - START TRANSACTION
          - "UPDATE foobar SET abc='xyz'"
          - ROLLBACK

#  "query_result": [[], [], []], "rowcount": [0, 42, 0]
```
