### ISSUE TITLE
mysql_variables persist and persist_only mode only for MySQL available?

### ISSUE THREAD

**Issue by rafi0101** [ansible-collections/ansible.mysql#620]
##### SUMMARY
mysql_variables with mode persist and persist_only is only available for MySQL and Version >= 8?

Why is this not possible for MariaDB and you exclude it from your tests?
[tests/integration/targets/test_mysql_variables/tasks/mysql_variables.yml#L438-L440](https://github.com/ansible-collections/community.mysql/blob/c99c19a489d0c1db85457bc8b7ffbeccf82788dd/tests/integration/targets/test_mysql_variables/tasks/mysql_variables.yml#L438-L440)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mysql.mysql_variables

##### ANSIBLE VERSION
```
ansible [core 2.16.4]
mariadb  Ver 15.1 Distrib 10.6.17-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

##### COLLECTION VERSION

```
community.mysql 3.9.0
```

##### STEPS TO REPRODUCE

```yaml
- name: "<mariadb_config> set custom variables to mariadb config"
  community.mysql.mysql_variables:
    variable: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: persist
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
```

##### ACTUAL RESULTS

```paste below
Error Message from ansible: "msg": "Server version must be 8.0 or greater."
```
