### ISSUE TITLE
`mysql_user`: can't get `plugin_hash_string` working with `caching_sha2_password`

### ISSUE THREAD

**Issue by Aohzan** [ansible-collections/ansible.mysql#621]
##### SUMMARY
Hello,
I use `caching_sha2_password` plugin for my users on MySQL 8 servers.
At beginning, I just use 
```yaml
- name: myyser
  community.mysql.mysql_user:
    name: myuser
    plugin_auth_string: "xxxxx"
    plugin: "caching_sha2_password"
```
but I had idempotence issue because, each time the password was marked as changed because the hash generated by MySQL was different.
So I tried to use `plugin_hash_string` instead of `plugin_auth_string` to provide directly the hash generated from ansible to avoid idempotence issue. Like
```yaml
- name: myyser
  community.mysql.mysql_user:
    name: myuser
    plugin_hash_string:  "$A$005$9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0fd02fe"
    plugin: "caching_sha2_password"
```
but I have many problems:
1. [the test done on this ansible module is wrong](https://github.com/ansible-collections/community.mysql/blob/bfe2fdc3ff8b94b14574cdade1639ce11877215c/tests/integration/targets/test_mysql_info/tasks/filter_users_info.yml#L210) it should use `plugin_hash_string` instead of `plugin_auth_string`
2. As hash generated by MySQL are not string and contains special character, I can't provide a correct hash from ansible, maybe I can initiate a PR to provide a base64 encoded hash that will be decoded before send to MySQL ? Like `plugin_hash_string = base64.b64decode(plugin_hash_base64).decode("utf-8")`
3. The lack of documentation of how generate a correct hash is a problem
I found [this](https://github.com/mysql/mysql-server/blob/ea7d2e2d16ac03afdd9cb72a972a95981107bf51/sql/auth/sha2_password.cc#L397) on MySQL source code, with the hash like `$A$005$salthash` (salf length 20, hash length 43) but cannot log with it. Maybe a correct example can be added to the ansible documentation ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```ansible [core 2.16.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```Collection      Version
--------------- -------
community.mysql 3.9.0  
----------------- -------
community.general 8.5.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Debian 12

##### STEPS TO REPRODUCE
example of hash
```yaml
- name: myyser
  community.mysql.mysql_user:
    name: myuser
    plugin_hash_string: "{{ '$A$005$' ~ 'abcdefghtrdlsorafgthe' ~ ('test' | hash('sha256'))[0:42] }}"
    plugin: "caching_sha2_password"
```

##### EXPECTED RESULTS
Changed hash, can connect with password before hash, and idempotence ok

##### ACTUAL RESULTS
Change hash, cannot connect with password
or
Hash not accepted by MySQL
