### ISSUE TITLE
GHA: add testing against MariaDB 10.11 LTS

### ISSUE THREAD

**Issue by laurent-indermuehle** [ansible-collections/ansible.mysql#625]
##### SUMMARY

The collection should test every LTS version of MariaDB. Currently 10.11 is not tested

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

tests

##### ADDITIONAL INFORMATION

In order to limit the number of tests, I think when we add a new version of a component, the collection should use only latests version of the other components. Namely Python, ansible-core and the connectors. So the new matrix could be something like this:

```yaml
strategy:
  matrix:
    ansible:
      - stable-2.15
      - stable-2.16
      - stable-2.17
      - devel
    db_engine_name:
      - mysql
      - mariadb
    db_engine_version:
      - '5.7.40'
      - '8.0.31'
      - '10.4.27'
      - '10.5.18'
      - '10.6.11'
    python:
      - '3.8'
      - '3.9'
      - '3.10'
    connector_name:
      - pymysql
      - mysqlclient
    connector_version:
      - '0.7.11'  # Released Apr 05, 2017
      - '0.9.3'    # Released Dec 18, 2018
      - '1.0.2'
      - '2.0.1'
      - '2.0.3'
      - '2.1.1'
    include:
      - db_engine_version: 10.11.7
        db_engine_name: mariadb
        ansible: stable-2.17
        python: '3.10' 
        connector_version: '0.9.3'
        connector_name: pymysql

      - db_engine_version: 10.11.7
        db_engine_name: mariadb
        ansible: stable-2.17
        python: '3.10' 
        connector_version: '2.1.1'
        connector_name: mysqlclient

```
