### ISSUE TITLE
Feature request: Add engine option to the mysql_info module?

### ISSUE THREAD

**Issue by chriscroome** [ansible-collections/ansible.mysql#644]
Currently `community.mysql.mysql_info` doesn't have an output for the database engine that is in use, MariaDB or MySQL, there are times when this is needed, for example the [Matomo](https://matomo.org/) database schema need to be set to `Mysql` or `Mariadb`:

```bash
php console config:get --section database --key schema
"Mariadb"
```

Currently I use this to get the schema from the database:

```yaml
    - name: "Check the database version using the details from {{ matomo_db_config }}"
      community.mysql.mysql_info:
        config_file: "{{ matomo_db_config }}"
        filter:
          - version
      register: matomo_mysql_info
  
    - name: Debug matomo_mysql_info
      ansible.builtin.debug:
        var: matomo_mysql_info
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"
  
    - name: Set a fact for the database type
      ansible.builtin.set_fact:
        matomo_db_type: "{{ matomo_mysql_info.version.suffix | ansible.builtin.regex_replace('-.*$') | capitalize | trim }}"  
```

And this to set it:

```yaml
    - name: Update the Matomo database schema
      ansible.builtin.command: "{{ matomo_php }} console --no-ansi -n config:set '{{ matomo_set_database_schema }}'"
      args:
        chdir: "{{ matomo_html }}"
      vars:
        matomo_set_database_schema: 'database.schema="{{ matomo_db_type }}"'
      become: true
      become_user: "{{ matomo_user }}"
      changed_when: true
```

It would be nicer if `mysql_info` returned something like this (`engine` has been added):

```yaml
    matomo_mysql_info:
        changed: false
        connector_name: pymysql
        connector_version: 1.0.2
        failed: false
        version:
            full: 10.11.6-MariaDB-0+deb12u1
            major: 10
            minor: 11
            release: 6
            suffix: MariaDB-0+deb12u1
            engine: MariaDB
```

So I could omit the `regex_replace`.
