### ISSUE TITLE
(1862, 'Your password   has expired. To log in you must change it using a client that supports expired   passwords.')

### ISSUE THREAD

**Issue by yunhai20082008** [ansible-collections/ansible.mysql#657]
##### SUMMARY
 unable to connect to database, check login_user and login_password are correct
  or /root/.my.cnf has the credentials. Exception message: (1862, 'Your password
  has expired. To log in you must change it using a client that supports expired
  passwords.')

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

MySQL-python
community.mysql.mysql_user
##### ANSIBLE VERSION

```paste below
AWX24.6.0
```

##### COLLECTION VERSION

```paste below
dockerfile

FROM quay.io/ansible/awx-ee:latest

    #WORKDIR /var/lib/awx
    USER root
	RUN ansible-galaxy collection install community.mysql

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

virtual box-vagrant-centos7
pxc8.0 
##### STEPS TO REPRODUCE

```yaml

---

- hosts: all
  become: true
  tasks:
    - name: centos7 install software
      ansible.builtin.yum:
        name:
          - MySQL-python
        state: present
      retries: 2
      delay: 2

    - name: Reset MySQL password for 'username'
      community.mysql.mysql_user:
        name: root
        password: xxxxxx
        host: localhost
        login_user: root
        login_password: xxxxxx

```

##### ACTUAL RESULTS

```paste below

```
