### ISSUE TITLE
Allow usage of RETAIN CURRENT PASSWORD clause when updating a password

### ISSUE THREAD

**Issue by pwakano** [ansible-collections/ansible.mysql#663]
##### SUMMARY

Allow usage of RETAIN CURRENT PASSWORD when updating a password

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

mysql_user

##### ADDITIONAL INFORMATION

MySQL 8.0.14 allows the use of RETAIN CURRENT PASSWORD, which are nice additions when handling password updates (https://dev.mysql.com/doc/mysql-security-excerpt/8.0/en/password-management.html#dual-passwords). The mysql_user module could support these options when updating a user's password.
I think this option could handled in the update_password parameter, but of course a new parameter would be fine too.
There is also the DISCARD OLD PASSWORD clause that could be supported as well to be fully up-to-date with the latest MySQL features and allow total control via Ansible.

```yaml
  mysql_user:
    login_host: "my_db_host"
    login_user: "my_admin"
    login_password: "my_admin_secret_password"
    name: "my_user"
    password: "my_user_new_password"
    update_password: "retain" # --> THIS IS NEW/PROPOSED

  mysql_user:
    login_host: "my_db_host"
    login_user: "my_admin"
    login_password: "my_admin_secret_password"
    name: "my_user"
    update_password: "discard_old" # --> THIS IS NEW/PROPOSED

```
