### ISSUE TITLE
add support for ed25519 password plugin in mysql_user

### ISSUE THREAD

**Issue by hubiongithub** [ansible-collections/ansible.mysql#672]
Followup to
https://github.com/ansible-collections/community.mysql/issues/6

##### SUMMARY
add ed25519 plugin support in mysql_user

##### ISSUE TYPE
allow user to create and alter mariadb user with ed25519 plugin

##### COMPONENT NAME
mysql_user, module_utils/user.py

##### ADDITIONAL INFORMATION
https://mariadb.com/kb/en/create-user/#identified-viawith-authentication_plugin

```
in v3.10.0 this starts at line 214:
        # Mysql and MariaDB differ in naming pam plugin and Syntax to set it
        if plugin in ('pam'):  # Used by MariaDB which requires the USING keyword, not BY
            query_with_args = "CREATE USER %s@%s IDENTIFIED WITH %s USING %s", (user, host, plugin, plugin_auth_string)
        elif plugin in ('ed25519'):  # Used by MariaDB which requires the USING keyword, not BY
            query_with_args = "CREATE USER %s@%s IDENTIFIED WITH %s USING PASSWORD(%s)", (user, host, plugin, plugin_auth_string)
        elif salt:            

and this at line 400:
                    # Mysql and MariaDB differ in naming pam plugin and syntax to set it
                    if plugin in ('pam'):                                                
                        query_with_args = "ALTER USER %s@%s IDENTIFIED WITH %s USING %s", (user, host, plugin, plugin_auth_string)
                    elif plugin in ('ed25519'):                                                
                        query_with_args = "ALTER USER %s@%s IDENTIFIED WITH %s USING PASSWORD(%s)", (user, host, plugin, plugin_auth_string)
                    elif salt:

```

According to the mentioned mariadb documentation, pam is using the "plugin_auth_string" as a string to identify the pam service
and ed25519 needs a hash or a cleartext password in the PASSWORD(%s) call. above code only works for the later one.
I tested these with ansible code like this:

```
- name: Create User
      community.mysql.mysql_user:
        name: "{{ user_monitoring }}"
        plugin: "ed25519"
        plugin_auth_string: "{{ user_monitoring_pw }}"
        update_password: "on_create"
        priv: 'monitoring.*:ALL/*.*:REPLICATION SLAVE ADMIN,SLAVE MONITOR'
        host: "{{ item }}"
        resource_limits:
          MAX_USER_CONNECTIONS: 10
        tls_requires:
          ssl:
        state: present
      with_items:
        - "localhost"
```
