### ISSUE TITLE
mysql_db: Add support for sql_log_bin

### ISSUE THREAD

**Issue by hyvs** [ansible-collections/ansible.mysql#700]
##### SUMMARY
The `mysql_user` module has an interesting feature that allows creating users without writing to the binary log:

```
community.mysql.mysql_user:
    name: foo
    ...
    sql_log_bin: false
```

This feature is particularly useful for provisioning all servers in a primary-replica cluster without breaking replication or needing to identify the primary server at any given time.

Could this be a valuable addition to the `mysql_db` module?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`mysql_db`

##### ADDITIONAL INFORMATION

```yaml
community.mysql.mysql_db:
  name: foo
  sql_log_bin: false # (default should be true)
  state: present
```
