### ISSUE TITLE
Support user account locking

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [ansible-collections/ansible.mysql#701]
##### SUMMARY
Support `ACCOUNT LOCK | ACCOUNT UNLOCK` in `CREATE USER` and `ALTER USER`

This is to create "system" accounts for stored procedures, see also:
https://mariadb.com/kb/en/account-locking/
https://dev.mysql.com/doc/refman/8.4/en/account-locking.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
This would just extend the user module.

##### ADDITIONAL INFORMATION
I think this could either be an additional state ie.

```
state: (present | locked | absent)
```

Example

```
- name: Create user for stored procedure
  become: yes
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: 'procedure_definer'
    priv: '{{ db_name }}.*:SELECT'
    state: locked
```

Or an additional option:

```
- name: Create user for stored procedure
  become: yes
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: 'procedure_definer'
    priv: '{{ db_name }}.*:SELECT'
    locked: yes
    state: present
```

I looked a bit at `user.py` and it seems to me that the best way to implement it would be in **serial** as in first run the current user creation logic and then lock/unlock because the alternative would double the current list of potential create user queries from 10 to 20

If I have time and there is a positive response to this issue I'll try to create a PR.
