### ISSUE TITLE
have setup multiple times on how to make it work in my main.spec.yml file but keep failing.

### ISSUE THREAD

**Issue by Lysander086** [ansible-collections/ansible.mysql#709]
##### SUMMARY

MySQL connection fails during Ansible playbook execution with error "Can't connect to MySQL server on 'localhost'"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.mysql.mysql_db

##### ANSIBLE VERSION

```
ansible [core 2.15.13]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/share/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/root/.local/share/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION
```
# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.13.0
```

##### CONFIGURATION
```
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT
- Linux environment (WSL)
- MySQL server running on port 3307
- MySQL credentials specified in playbook

##### STEPS TO REPRODUCE
Run the following playbook to connect to MySQL database:

```yaml
---
- hosts: 127.0.0.1
  vars_files:
  - "{{ lookup('env', 'WORK_DIR') }}/service_distributions/playbooks/inventories/local/host_vars/anchor_host_vars.yml"

  tasks:
  - name: Output connection info
    debug:
      msg: >
        "Connection info: user={{ 'root' }}, host={{ groups['db_servers'] }}, port={{ DB_PORT }}, DB_ROOT_PASSWORD={{ DB_ROOT_PASSWORD }}, inventory groups={{ group_names }}"

  - name: Connect and retrieve list of databases
    community.mysql.mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: anchor-db
      login_user: root
      login_password: PASSWORD 
      login_host: 127.0.0.1
      login_port: 3307
      state: present
    register: db_info
```

##### EXPECTED RESULTS
The playbook should successfully connect to the MySQL server running on localhost:3307, create the 'anchor-db' database if it doesn't exist, and retrieve a list of existing databases.

##### ACTUAL RESULTS
The connection to MySQL fails with socket error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2003, \"Can't connect to MySQL server on 'localhost' ([Errno 2] No such file or directory)\")"}
```

The issue appears to be related to the MySQL socket file path. The error indicates that Ansible is trying to connect via socket file but cannot find it at the specified location. As a workaround, we've modified the playbook to use direct shell commands instead:

```yaml
- name: Connect and retrieve list of databases using shell
  shell: >
    mysql -u root -p'PASSWORD' -h 127.0.0.1 -P 3307 -e "CREATE DATABASE IF NOT EXISTS \`anchor-db\`; SHOW DATABASES;"
  register: db_info
```

This shell-based approach works correctly while the community.mysql module fails.

**Comment by markuman** [comment]
```diff
  - name: Connect and retrieve list of databases
    community.mysql.mysql_db:
-      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: anchor-db
      login_user: root
      login_password: PASSWORD 
      login_host: 127.0.0.1
      login_port: 3307
      state: present
    register: db_info
```

have you try to drop the `login_unix_socket` parameter?

**Comment by Lysander086** [comment]
> - name: Connect and retrieve list of databases
>     community.mysql.mysql_db:
> -      login_unix_socket: /var/run/mysqld/mysqld.sock
>       name: anchor-db
>       login_user: root
>       login_password: PASSWORD 
>       login_host: 127.0.0.1
>       login_port: 3307
>       state: present
>     register: db_info
> have you try to drop the `login_unix_socket` parameter?

Thanks very much for helping out. the below playbook work for me in `main.spec.yml`
```yaml
---
- hosts: db_servers
  vars_files:
    - "{{ lookup('env', 'WORK_DIR') }}/service_distributions/playbooks/inventories/local/host_vars/anchor_host_vars.yml"

  tasks:
    - name: Connect to created database instance.
      community.mysql.mysql_db:
        name: information_schema
        login_user: root
        login_password: "{{ DB_ROOT_PASSWORD }}"
        login_host: "{{ db_host }}"
        login_port:  "{{ DB_PORT }}"
        state: present
      register: db_connection_result
    - name: Debug the database info
      ansible.builtin.debug:
        var: db_connection_result
    - name: Ensure the database provisioning was successful
      ansible.builtin.assert:
        that:
          - db_connection_result is succeeded
          - db_connection_result.db_info is defined
          - "'information_schema' in db_connection_result"
        msg: >
          Cannot verify that the database provisioning was successful: "{{ db_connection_result }}"
```
