### ISSUE TITLE
MariaDB + user default role breaks

### ISSUE THREAD

**Issue by Xjs** [ansible-collections/ansible.mysql#710]
##### SUMMARY

I use MariaDB (11.7.2) and I have a user in my database that has a default role granted (using
```
SET DEFAULT ROLE `somerole` FOR `someuser`@`%`
```
). The mysql_user module expects the output of `SHOW GRANTS` to be always of the form `GRANT …` when using MariaDB. Therefore when encountering a user with a role grant such as the above, the execution fails with 
```
someuser...
  <server> failed | msg: unable to parse the MySQL grant string: SET DEFAULT ROLE `somerole` FOR `someuser`@`%`
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.14]
  config file = /Users/jannis/src/bitbucket.org/vauwede/iq-baremetal/manage/ansible.cfg
  configured module search path = ['/Users/jannis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible@9/9.13.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/jannis/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.10 (main, Apr  8 2025, 11:35:47) [Clang 16.0.0 (clang-1600.0.26.6)] (/opt/homebrew/Cellar/ansible@9/9.13.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /Users/jannis/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.13.0

# /opt/homebrew/Cellar/ansible@9/9.13.0/libexec/lib/python3.12/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.11.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/jannis/src/<redacted>/manage/ansible.cfg
DEFAULT_LOG_PATH(/Users/jannis/src/<redacted>/manage/ansible.cfg) = /Users/jannis/src/<redacted>/manage/ansible.log
DEFAULT_REMOTE_USER(/Users/jannis/src/<redacted>/manage/ansible.cfg) = automation
DEFAULT_ROLES_PATH(/Users/jannis/src/<redacted>/manage/ansible.cfg) = ['/Users/jannis/src/<redacted>/manage/galaxy_roles', '/Users/jannis/src/<redacted>/manage/roles>
DEFAULT_STDOUT_CALLBACK(/Users/jannis/src/<redacted>/manage/ansible.cfg) = community.general.unixy
DEPRECATION_WARNINGS(/Users/jannis/src/<redacted>/manage/ansible.cfg) = False
EDITOR(env: EDITOR) = vim
HOST_KEY_CHECKING(/Users/jannis/src/<redacted>/manage/ansible.cfg) = False
INVENTORY_ENABLED(/Users/jannis/src/<redacted>/manage/ansible.cfg) = ['yaml']
```

##### OS / ENVIRONMENT

Source OS: macOS 15.3.1
Target OS: Oracle Linux Server 8.10

##### STEPS TO REPRODUCE
can add later if unclear (pressed for time rn)

**Comment by Andersson007** [comment]
@Xjs hello, thanks for reporting the issue!
I'll put the help wanted label to indicate that the issue is vacant for digging deeper
There's a quick start [guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) that can help

**Comment by laurent-indermuehle** [comment]
Hi @Xjs,
I'm fixing an issue about MariaDB roles right now: #712 so I'm not surprised that you had a similar kind of error. We do not support roles very well.

It is not clear how you used the mysql_user module to produce the error. Could you provide an example please?
Are you trying to use the `mysql_user` to grants privileges to a role?

But, I must admit that I don't think we will fix this issue. Roles between MySQL and MariaDB are different and are a mess to manage. I don't see a big value for roles when you already have everything automated with Ansible.

**Comment by TimKruth02** [comment]
Hey.

We currently have the same problem in our company. I will try to submit a pull request in the next week.

**Comment by Andersson007** [comment]
> Hey.
> 
> We currently have the same problem in our company. I will try to submit a pull request in the next week.

@TimKruth02 hello, it'd be great, thanks! The quick start dev [guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) can be helpful, fyi

**Comment by laurent-indermuehle** [comment]
@TimKruth02 contributions are always welcome.

Do your company uses MariaDB roles?  Or MySQL ones? Do you use the DEFAULT role too?

**Comment by TimKruth02** [comment]
@laurent-indermuehle @Andersson007 thanks for the warm welcome.

We currently only use mariadb and the DEFAULT role was added manually and now causes the module to fail.

I would use this comment to clarify the current issue by adding the steps to reproduce. I have already created a test case which looks like this:

```yaml
---
- vars:
    mysql_parameters: &mysql_params
      login_user: '{{ mysql_user }}'
      login_password: '{{ mysql_password }}'
      login_host: '{{ mysql_host }}'
      login_port: '{{ mysql_primary_port }}'

  block:
    - name: Create role to use as default
      community.mysql.mysql_role:
        <<: *mysql_params
        name: developers
        state: present
        priv: '*.*:ALL'
        members:
        - "{{ user_name_1 }}@localhost"

    - name: Set default role for db_user1
      community.mysql.mysql_query:
        <<: *mysql_params
        query: "SET DEFAULT ROLE developers for {{ user_name_1 }}@localhost"

    - name: Show grants for user1
      command: "{{ mysql_command }} -e \"SHOW GRANTS FOR '{{ user_name_1 }}'@'localhost'\""
      register: result

    - name: Ensure user can still be altered
      mysql_user:
        <<: *mysql_params
        name: "{{ user_name_1 }}"
        password: "{{ user_password_1 }}"
        priv: '*.*:ALL'
        state: present
      register: result
``` 
I ran this playbook against the Docker image “mariadb:11.4.5”, which results in the following output:

```bash
TASK [test_mysql_user : include_tasks] *****************************************
included: /root/ansible_collections/community/mysql/tests/output/.tmp/integration/test_mysql_user-rd760wz3-ÅÑŚÌβŁÈ/tests/integration/targets/test_mysql_user/tasks/issue-710.yml for testhost

TASK [test_mysql_user : Create user with DEFAULT privileges] *******************
changed: [testhost] => {"attributes": null, "changed": true, "msg": "User added", "password_changed": true, "user": "db_user1"}

TASK [test_mysql_user : Create role to use as default] *************************
[WARNING]: Option column_case_sensitive is not provided. The default is now
false, so the column's name will be uppercased. The default will be changed to
true in community.mysql 4.0.0.
changed: [testhost] => {"changed": true}

TASK [test_mysql_user : Set default role for db_user1] *************************
ok: [testhost] => {"changed": false, "executed_queries": ["SET DEFAULT ROLE developers for db_user1@localhost"], "execution_time_ms": [1.5267], "query_result": [[]], "rowcount": [0]}

TASK [test_mysql_user : Show grants for user1] *********************************
changed: [testhost] => {"changed": true, "cmd": ["mysql", "-h10.88.0.1", "-P3307", "-uroot", "-pmsandbox", "--protocol=tcp", "-e", "SHOW GRANTS FOR 'db_user1'@'localhost'"], "delta": "0:00:00.011189", "end": "2025-06-16 09:15:44.289582", "msg": "", "rc": 0, "start": "2025-06-16 09:15:44.278393", "stderr": "", "stderr_lines": [], "stdout": "Grants for db_user1@localhost\nGRANT `developers` TO `db_user1`@`localhost`\nGRANT USAGE ON *.* TO `db_user1`@`localhost` IDENTIFIED BY PASSWORD '*3C991CFA432A1347EB705C7A9F99A28B0967072A'\nSET DEFAULT ROLE `developers` FOR `db_user1`@`localhost`", "stdout_lines": ["Grants for db_user1@localhost", "GRANT `developers` TO `db_user1`@`localhost`", "GRANT USAGE ON *.* TO `db_user1`@`localhost` IDENTIFIED BY PASSWORD '*3C991CFA432A1347EB705C7A9F99A28B0967072A'", "SET DEFAULT ROLE `developers` FOR `db_user1`@`localhost`"]}

TASK [test_mysql_user : Ensure user can still be altered] **********************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "unable to parse the MySQL grant string: SET DEFAULT ROLE `developers` FOR `db_user1`@`localhost`"}
```

As you can see the  "SHOW GRANTS FOR 'db_user1'@'localhost'" returns "SET DEFAULT ROLE `developers` FOR `db_user1`@`localhost`", which the mysql_user module can not handle.
