### ISSUE TITLE
MariaDB incompatible auth plugin syntax

### ISSUE THREAD

**Issue by Skgland** [ansible-collections/ansible.mysql#719]
##### SUMMARY

`community.mysql.mysql_user` with `plugin:` and `plugin_auth_string:` doesn't work with MariaDB.
Depending on if `salt:` is also specified a different syntax error is encountered.

Related #262

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Task: `community.mysql.mysql_user`

##### ANSIBLE VERSION

```
ansible [core 2.16.3]
  config file = <REDACTED>
  configured module search path = ['/home/<REDACTED>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/<REDACTED>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<REDACTED>/.local/bin/ansible
  python version = 3.12.3 (main, May 26 2025, 18:50:19) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/<REDACTED>/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.13.0 

# /usr/lib/python3/dist-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.8.0 
```

From playbook run with -vvvv:

`Using module file /home/<REDACTED>/.ansible/collections/ansible_collections/community/mysql/plugins/modules/mysql_user.py`

##### CONFIGURATION

```paste below
CONFIG_FILE() = <REDACTED>
DEFAULT_VAULT_PASSWORD_FILE(<REDACTED>) = <REDACTED>
```

###### Controller: 

WSL2

```
$> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

###### Remote Host:
```
$> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

$> apt list mariadb-server
Listing... Done
mariadb-server/stable,now 1:10.11.11-0+deb12u1 arm64 [installed]
mariadb-server/stable 1:10.11.11-0+deb12u1 armhf
```

##### STEPS TO REPRODUCE

Without `salt:`

```yaml
- name: Create MariaDb user
  become: true
  community.mysql.mysql_user:
    column_case_sensitive: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: usern_name
    password_expire: never
    plugin: caching_sha2_password
    plugin_auth_string : user_password
    priv: "*.*:ALL,GRANT"
```

With `salt:`

```yaml
- name: Create MariaDb user
  become: true
  community.mysql.mysql_user:
    column_case_sensitive: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: usern_name
    password_expire: never
    plugin: caching_sha2_password
    plugin_auth_string : user_password
    salt: 1234567890abcdefghij
    priv: "*.*:ALL,GRANT"
```

##### EXPECTED RESULTS
User is created with the specified auth plugin and password (salted using the provided salt)

##### ACTUAL RESULTS

Without `salt:`

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'user_password'' at line 1`

With `salt:`

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0xDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEAD...' at line 1`

Note: hex value has been changed to a dummy value
