### ISSUE TITLE
No way to connect via TCP?

### ISSUE THREAD

**Issue by SturmB** [ansible-collections/ansible.mysql#85]
##### SUMMARY

I receive an error message when using the `mysql_db` module to connect to a MySQL Docker container.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_db

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /home/sturm/devops/ansible.cfg
  configured module search path = ['/home/sturm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sturm/.local/lib/python3.8/site-packages/ansible
  executable location = /home/sturm/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/sturm/devops/ansible.cfg) = ['/home/sturm/devops/inventories/main']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/sturm/devops/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/sturm/devops/ansible.cfg) = ['/home/sturm/devops/roles']
DEFAULT_STDOUT_CALLBACK(/home/sturm/devops/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/home/sturm/devops/ansible.cfg) = /home/sturm/devops/.vault_pass
HOST_KEY_CHECKING(/home/sturm/devops/ansible.cfg) = False
INTERPRETER_PYTHON(/home/sturm/devops/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

Host:
Windows 10 v2004 with WSL2 running Ubuntu 20.04
Target:
Ubuntu 18.04

##### STEPS TO REPRODUCE

1. Ensure that a MySQL Docker container is up and running on the target with some data.
2. Write a simple playbook using the task below. (Replace the variables with your own info.)
3. Run the playbook and watch the error message appear:
```
fatal: [skyubuntu]: FAILED! => changed=false
  msg: |-
    mysqldump: [Warning] Using a password on the command line interface can be insecure.
    mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect
```

Here's the task for calling the mysqldump process:
```yaml
  tasks:
    - name: Dump Sky Schedule database
      community.mysql.mysql_db:
        name: "{{ db_database }}"
        state: dump
        target: /tmp/{{ db_database }}.sql
        login_host: localhost
        login_port: 3306
        login_user: "{{ vault_db_username }}"
        login_password: "{{ vault_db_password }}"
```

##### EXPECTED RESULTS

I expect the module to connect to the MySQL server via TCP.

##### ACTUAL RESULTS

The module appears to be trying to connect to the MySQL container via a unix socket. Per [this SO answer](https://stackoverflow.com/a/34489879/2379279), the only way to connect to a MySQL container is to specifically set the protocol to TCP. I see no way to do so with `mysql_db`.

```paste below
 ___________________________________
< TASK [Dump Sky Schedule database] >
 -----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[WARNING]: Module did not set no_log for unsafe_login_password
fatal: [skyubuntu]: FAILED! => changed=false
  msg: |-
    mysqldump: [Warning] Using a password on the command line interface can be insecure.
    mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect
```
